### ISSUE TITLE
Tag based on Dataset column

### ISSUE THREAD

**Issue by oersted** [enjalot/latent-scope#19]
The main use case I have for this tool is to analyze samples for a classification task.

It would be great if samples could be automatically tagged by their label.
It would also be great if the points in the visualization could have some visual distinction based on their tag.

Also, a minor note: boolean values don't seem to be ingested properly from a CSV, they appear empty in the UI.

**Comment by enjalot** [comment]
@oersted Would you be able to share a sample of the data you were importing? I'd like to see exactly how the booleans get treated (I'm just reading with pandas.read_csv).

In terms of using a label, would it be helpful to have the option to color by label (and have a legend) rather than coloring by cluster? Another feature I've been thinking about is the ability to filter by a field in the dataset, so you could choose a label and see those points highlighted on the umap.

**Comment by enjalot** [comment]
You can now filter on categorical columns (with 20 or fewer unique values) in 0.2.0
you can then bulk tag or change their cluster when filtering by column
